version: "3"
services:
      client:
          image: client
          build: 
            dockerfile: ./client/Dockerfile
          container_name: client
          ports:
              - "3000:3000"        
          volumes: 
              - ./:/client
              - /client/node_modules
      db:
        image: postgres:14.1-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432:5432'
        volumes: 
          - db:/server/data
      server:
        build: 
          dockerfile: ./server/Dockerfile
        container_name: server
        image: server
        depends_on:
          - db
        ports:
          - 8080:8080
        environment:
          NODE_ENV: production
          DB_HOST: db
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: postgres
        links:
          - db
        volumes:
          - './:/server'
volumes:
  db:
    driver: local