version: "3"
services:
      client:
          image: client
          build: /client
          container_name: client
          ports:
              - "3000:3000"        
      db:
        image: postgres:14.1-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432:5432'
        volumes: 
          - db:/data
      server:
        build: /server
        container_name: server
        image: server
        depends_on:
          - db
        ports:
          - 8080:8080
        environment:
          NODE_ENV: production
          DB_HOST: db
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: postgres
        links:
          - db
volumes:
  db:
    driver: local