#Each instruction in this file creates a new layer
#Here we are getting our node as Base image
FROM node:latest
#setting working directory in the container
WORKDIR /server
COPY package.json .
COPY yarn.lock .
RUN npm install -g
RUN yarn install
COPY . ./
#container exposed network port number
EXPOSE 8080
#command to run within the container
CMD ["node", "app.js"]